repos:
  - repo: https://gitlab.com/vojko.pribudic.foss/pre-commit-update
    rev: v0.6.1
    hooks:
    - id: pre-commit-update
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^tests/fixtures/
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.14.0
    hooks:
    - id: reorder-python-imports
      args: [
          --application-directories, '.',
          --py38-plus,
          --add-import, 'from __future__ import annotations',
        ]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.7.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.9.7
    hooks:
      - id: ruff
        args: [ --fix ]
      - id: ruff-format
