repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    - id: check-yaml
    - id: debug-statements
    - id: end-of-file-fixer
    - id: trailing-whitespace
      exclude: ^tests/fixtures/
  - repo: https://github.com/asottile/reorder-python-imports
    rev: v3.12.0
    hooks:
    - id: reorder-python-imports
      args: [
          --application-directories, '.:PROJECT',
          --py38-plus,
          --add-import, 'from __future__ import annotations',
        ]
  - repo: https://github.com/asottile/setup-cfg-fmt
    rev: v2.5.0
    hooks:
      - id: setup-cfg-fmt
  - repo: https://github.com/psf/black-pre-commit-mirror
    rev: 24.4.2
    hooks:
      - id: black
        language_version: python3.10
  - repo: https://github.com/PyCQA/flake8
    rev: 7.0.0
    hooks:
      - id: flake8
